### ISSUE TITLE
Clicar em concluir a venda quando ainda nao autenticado.

### ISSUE THREAD

**Issue by luizjamp** [cagartner/bagisto-brazilcustomer#1]
Se a pessoa ainda nao se logou , coloca um item no carrinho, depois clique em concluir.
aparece o segunte erro:
Trying to get property 'person_type' of non-object

Open: F:\laragon\www\bagisto\vendor\cagartner\bagisto-brazilcustomer\src\Listeners\VerifyUserDataListenerCheckout.php
$customer = auth()->guard('customer')->user();

if (!$customer->person_type || !$customer->document) {
        Session()->flash('error', trans('You registration need to be completed, please update you register before buy.'));

O problema é que se ainda não esta registrado, não existe o $customer ainda, entao acho que deve ser assim:
if **($customer = Null &&** ( !$customer->person_type || !$customer->document))

**Comment by cagartner** [comment]
Mergeado o Pull request do @beautiful-sea que corrige esse problema.

Atualize seu código e tente novamente.
