### ISSUE TITLE
Erro na Instalação !!!

### ISSUE THREAD

**Issue by luizjamp** [cagartner/bagisto-brazilcustomer#3]
Apresentou o seguinte erro em 20/05/20
Installation failed, reverting ./composer.json to its original content.

  [Composer\Downloader\TransportException]
  The "http://repo.packagist.org/p/illuminate/translation%248ecb5b2152ae873f81418d3a750f916cd22f0b98445e04fccc619f1bf0c9c5b8.json" file could not be downloaded: php_network_getaddresses: getaddrinfo
   failed: Name or service not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by cagartner** [comment]
Esse erro é referente ao um problema com sua internet, ele não ta conseguindo baixar o pacote, outra coisa ele é referente a um pacote do core do laravel, nem é referente a extensão do bagisto.
